### ISSUE TITLE
Help! About Utilities tool

### ISSUE THREAD

**Issue by banktakumi** [priitj/whitedb#33]
What is it work?
1. wgdb query col "cond" value .. - basic query.
2. wgdb del col "cond" value .. - like query. Matching rows are deleted from database.

I don't understand what is col and cond and how to delete row when i have to add value in shm?

Show me the example please. Thank you.

**Comment by necrophcodr** [comment]
You can read the tutorial here: https://github.com/priitj/whitedb/blob/master/Doc/Tutorial.txt

It explains fully how the wgdb tool works. Don't forget that wgdb is just a tool. As far as I know, WhiteDB is supposed to be embedded in your C application.
