### ISSUE TITLE
wgdb ls or is there a way to list all databases in memory?

### ISSUE THREAD

**Issue by aleksandergabriel** [priitj/whitedb#38]
Pretty much what the title is asking. I was reading through documentation for wgdb tool and and c api and was unable to find anything that would show me all databases in system. Is there such feature?

**Comment by priitj** [comment]
Hi, I've used the command
```
ipcs -m
```
successfully. The key in that listing is the same thing as the "shmname" parameter for the `wgdb` command, in hexadecimal.
