### ISSUE TITLE
http://whitedb.org/ is down

### ISSUE THREAD

**Issue by Koulwa** [priitj/whitedb#50]
Forbidden
You don't have permission to access / on this server.
Apache/2.4.39 Server at whitedb.org Port 80

Something's wrong on the server ... I know the documentation is also in the repo. But since the readme's here point to that URL probably something that should be fixed.

Switch the domain to GitHub, so you don't have to worry about hosting. It seems that's the likely problem. I know I've forgotten to pay the bill on sites before ...

**Comment by priitj** [comment]
Thanks, will look into this.

Since I'm not currently managing the hosting, this might take a while to sort out.
