### ISSUE TITLE
Using whitedb between (docker) containers

### ISSUE THREAD

**Issue by oak-tree** [priitj/whitedb#56]
Hey, 
If I understand correctly, `whitedb` uses `shm`  as `ipc`. 
If I set ipc as host for the container. Does whitedb can work between containers? 
Thanks
Alon

**Comment by necrophcodr** [comment]
You'd need to make a shared mount of `/dev/shm` of the host OS if I recall correctly. This is not something that docker inherently supports. I'll look into it within the next 6 hours and post an update, if you've not already resolved the issue on your own.

**Comment by priitj** [comment]
Hi, I'm assuming this question was resolved, thanks for the answer.
