### ISSUE TITLE
BUILD FAIL: configure cannot guess build type

### ISSUE THREAD

**Issue by xctan** [priitj/whitedb#63]
The config.guess file contains in the source code is too old that fail to build on latest architecture, such as RISC-V. This can be fixed by generating new tarball by latest autotools.

**Comment by necrophcodr** [comment]
Maybe I'm blind but what is the config.guess file you're referring to? I don't see it in the repository.

**Comment by xctan** [comment]
It's shipped with the source code tarball. Outdated release process (e.g. using old distros) may bring about such problem.

configure complains that it cannot determine the platform:

```
This script, last modified 2012-12-29, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2012-12-29

uname -m = riscv64
uname -r = 6.0.7-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000
```

As shown above, the config.guess timestamp is 2012-12-29, much bofore risc-v support was added to the toolchain, thus lacking support for it.

Could you please revise the process of releasing source code tarballs? For example, make sure the autotools package is up to date, or try to trigger force reconfiguration (e.g. `autoreconf -fiv`).

**Comment by necrophcodr** [comment]
@xctan the last tarball release is from 2014 though, and the config.guess in that is from 2013 it seems. Maybe it's better to use a specific tag and fetch the tarball of the source code directly from GitHub instead?

**Comment by priitj** [comment]
Should I do something with these old tarballs though? I guess the obvious response would be, release a new one but the development process stalled before I got 0.8 feature-complete. So it's some dr. Frankenstein version in the master branch right now. I suppose most people won't notice or mind.

**Comment by xctan** [comment]
Thanks for releasing an updated version (also the first release since 2014)! Even though it is still immature to be updated in the repository of Arch Linux, we are able to build this package on riscv platform out of the box. Hopefully a full-fledged 0.8 version will come true in the near future.
